In [1]:
!pip install pandas_datareader

Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from pandas_datareader) (1.3.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas_datareader) (4.2.6)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pandas_datareader) (2.23.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas_datareader) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas_datareader) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas_datareader) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas_datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas_datareader) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas_datareader) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas_datareader) (3.0.4)

In [9]:
from pandas_datareader import data
import datetime
import pandas as pd

In [10]:
data = 'FB.csv'
path = pd.read_csv(data)
df = pd.DataFrame(path)
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-01-04,274.779999,275.000000,265.200012,268.940002,268.940002,15106100
1,2021-01-05,268.290009,272.399994,268.209991,270.970001,270.970001,9871600
2,2021-01-06,262.000000,267.750000,260.010010,263.309998,263.309998,24354100
3,2021-01-07,265.899994,271.609985,264.779999,268.739990,268.739990,15789800
4,2021-01-08,268.309998,268.950012,263.179993,267.570007,267.570007,18528300
...,...,...,...,...,...,...,...
246,2021-12-23,330.100006,336.670013,328.359985,335.239990,335.239990,13987700
247,2021-12-27,338.850006,347.869995,338.010010,346.179993,346.179993,17795000
248,2021-12-28,346.630005,352.709991,345.200012,346.220001,346.220001,16637600
249,2021-12-29,346.910004,349.690002,341.640015,342.940002,342.940002,10747000
250,2021-12-30,344.000000,347.230011,343.220001,344.359985,344.359985,10593300

In [11]:
moving_column = df.pop('Open')
df.insert(3,'Open', moving_column)
df.head()

,Date,High,Low,Open,Close,Adj Close,Volume
0,2021-01-04,275.000000,265.200012,274.779999,268.940002,268.940002,15106100
1,2021-01-05,272.399994,268.209991,268.290009,270.970001,270.970001,9871600
2,2021-01-06,267.750000,260.010010,262.000000,263.309998,263.309998,24354100
3,2021-01-07,271.609985,264.779999,265.899994,268.739990,268.739990,15789800
4,2021-01-08,268.950012,263.179993,268.309998,267.570007,267.570007,18528300

In [12]:
def inc_dec(c, o):
  if c > o:
    value = "Increase"
  elif c < o:
    value= "Decrease"
  else:
    value= "Equal"

  return value

df["Status"] = [inc_dec(c,o) for c,o in zip(df.Close, df.Open)]

In [13]:
df

,Date,High,Low,Open,Close,Adj Close,Volume,Status
0,2021-01-04,275.000000,265.200012,274.779999,268.940002,268.940002,15106100,Decrease
1,2021-01-05,272.399994,268.209991,268.290009,270.970001,270.970001,9871600,Increase
2,2021-01-06,267.750000,260.010010,262.000000,263.309998,263.309998,24354100,Increase
3,2021-01-07,271.609985,264.779999,265.899994,268.739990,268.739990,15789800,Increase
4,2021-01-08,268.950012,263.179993,268.309998,267.570007,267.570007,18528300,Decrease
...,...,...,...,...,...,...,...,...
246,2021-12-23,336.670013,328.359985,330.100006,335.239990,335.239990,13987700,Increase
247,2021-12-27,347.869995,338.010010,338.850006,346.179993,346.179993,17795000,Increase
248,2021-12-28,352.709991,345.200012,346.630005,346.220001,346.220001,16637600,Decrease
249,2021-12-29,349.690002,341.640015,346.910004,342.940002,342.940002,10747000,Decrease
250,2021-12-30,347.230011,343.220001,344.000000,344.359985,344.359985,10593300,Increase

In [14]:
df['Middle'] = (df.Open + df.Close)/2
df['Height'] = abs(df.Close - df.Open)
df

,Date,High,Low,Open,Close,Adj Close,Volume,Status,Middle,Height
0,2021-01-04,275.000000,265.200012,274.779999,268.940002,268.940002,15106100,Decrease,271.860000,5.839997
1,2021-01-05,272.399994,268.209991,268.290009,270.970001,270.970001,9871600,Increase,269.630005,2.679992
2,2021-01-06,267.750000,260.010010,262.000000,263.309998,263.309998,24354100,Increase,262.654999,1.309998
3,2021-01-07,271.609985,264.779999,265.899994,268.739990,268.739990,15789800,Increase,267.319992,2.839996
4,2021-01-08,268.950012,263.179993,268.309998,267.570007,267.570007,18528300,Decrease,267.940002,0.739991
...,...,...,...,...,...,...,...,...,...,...
246,2021-12-23,336.670013,328.359985,330.100006,335.239990,335.239990,13987700,Increase,332.669998,5.139984
247,2021-12-27,347.869995,338.010010,338.850006,346.179993,346.179993,17795000,Increase,342.515000,7.329987
248,2021-12-28,352.709991,345.200012,346.630005,346.220001,346.220001,16637600,Decrease,346.425003,0.410004
249,2021-12-29,349.690002,341.640015,346.910004,342.940002,342.940002,10747000,Decrease,344.925003,3.970002
250,2021-12-30,347.230011,343.220001,344.000000,344.359985,344.359985,10593300,Increase,344.179993,0.359985

In [26]:
from bokeh.plotting import figure, show, output_file

p = figure(x_axis_type = 'datetime', width = 1000, height = 300)
p.title.text = "Candlestick Chart"
hours_12 = 12*60*60*1000

#Tăng 
p.rect(df.index[df.Status == "Increase"], df.Middle[df.Status == "Increase"],
       hours_12, df.Height[df.Status =="Increase"], fill_color="green",
       line_color="black")

#Giảm
p.rect(df.index[df.Status == "Decrease"], df.Middle[df.Status == "Decrease"],
       hours_12, df.Height[df.Status =="Decrease"], fill_color="red",
       line_color="black")

p.segment(df.index, df.High, df.index, df.Low, color = 'black')
show(p)